--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bancho-service-api
  labels:
    app: bancho-service-api
spec:


  template:
    metadata:
      labels:
        app: bancho-service-api
    spec:
      containers:
      - name: bancho-service-api
        image: tylere431/bancho-service:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: osu-speedrun-secrets
        env:
        - name: APP_COMPONENT
          value: api
        volumeMounts:
        - name: filters-config
          mountPath: /pep.py/filters.txt
          subPath: filters.txt
          readOnly: true
        resources:
          limits:
            cpu: "1000m"
            memory: "350Mi"
          requests:
            cpu: "200m"
            memory: "250Mi"
      volumes:
      - name: filters-config
        configMap:
          name: bancho-filters

--- 
apiVersion: v1
kind: Service
metadata:
  name: bancho-service-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: bancho-service-api


