--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hanayo
  labels:
    app: hanayo
spec:
  replicas: 1  # initial replica count, matching autoscaling minReplicas
  selector:
    matchLabels:
      app: hanayo
  template:
    metadata:
      labels:
        app: hanayo
    spec:
      containers:
      - name: hanayo
        image: tylere431/hanayo:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: osu-speedrun-secrets
        env:
        - name: APP_COMPONENT
          value: api
        resources:
          limits:
            cpu: "300m"
            memory: "250Mi"
          requests:
            cpu: "100m"
            memory: "150Mi"

--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hanayo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hanayo
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

--- 
apiVersion: v1
kind: Service
metadata:
  name: hanayo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hanayo