---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "db.default.svc.cluster.local"
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: osu-speedrun-secrets
                  key: DB_USER
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osu-speedrun-secrets
                  key: DB_PASS
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osu-speedrun-secrets
                  key: DB_PASS
            - name: PMA_ARBITRARY
              value: "0"  # Disable arbitrary server connections for security
            - name: HIDE_PHP_VERSION
              value: "true"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: phpmyadmin

