
apiVersion: apps/v1
kind: Deployment
metadata:
  name: score-service
  namespace: default
  labels:
    app: score-service
    component: api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1  
  selector:
    matchLabels:
      app: score-service
      component: api
  template:
    metadata:
      labels:
        app: score-service
        component: api
    spec:
      containers:
      - name: score-service
        image: tylere431/score-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        
        envFrom:
        # Mount all config from ConfigMap
        - configMapRef:
            name: score-service-config
        # Mount all secrets as environment variables
        - secretRef:
            name: osu-speedrun-secrets
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: score-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: score-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: score-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bancho-service-api
  minReplicas: 2
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
